name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "51 2 * * 1,4"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # ensure workflow_dispatch only runs on main
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v20
