name: "Check flake.lock"
on:
  push:
    branches: ["main"]
    paths:
      - '**.nix'
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
jobs:
  health-check:
    name: "Check health of `flake.lock`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
